import { createSlice } from '@reduxjs/toolkit'
import type { PayloadAction } from '@reduxjs/toolkit'
import { IUser } from '../models/user.model'

// Define a type for the slice state
interface IuserState {      //interface is used to define the shape of the state of the user slice
  userData:IUser | null
}

// Define the initial state using that type
const initialState: IuserState = {      //initial state of the user slice
  userData:null
}

export const userSlice = createSlice({      //createSlice is a function that accepts an initial state, an object of reducer functions, and a "slice name", and automatically generates action creators and action types that correspond to the reducers and state.
  name: 'user',
  // `createSlice` will infer the state type from the `initialState` argument
  initialState,
  reducers: {       //reducers are functions that take the current state and an action as arguments and return a new state. They are used to update the state in response to actions dispatched to the store.
    setUserData: (state, action) => {
      state.userData = action.payload       //setUserData is a reducer function that takes the current state and an action as arguments and updates the userData property of the state with the payload of the action. The payload of the action is expected to be of type IUser or null.
    }
  },
})

export const { setUserData } = userSlice.actions        //setUserData is an action creator that is generated by createSlice. It is a function that takes a payload as an argument and returns an action object with the type 'user/setUserData' and the payload as the value of the payload property of the action object.


export default userSlice.reducer        //userSlice.reducer is the reducer function that is generated by createSlice. It is a function that takes the current state and an action as arguments and returns a new state based on the reducers defined in the createSlice function. It is exported as the default export of the module so that it can be imported and used in the store configuration.